# name: Tag Release
# on:
#   push:
#     branches:
#       - main
#     tags:
#       - 'v*.*.*'

# jobs:
#   tag_release:
#     name: Tag the release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       # Step to fetch the current version from the package.json or any other version file.
#       # Modify this step according to your repository structure.
#       - name: Get current version
#         id: get_version
#         run: echo "::set-output name=version::$(cat version.txt)"  

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'  # Adjust the version if needed

#       - name: Install dependencies
#         run: npm install  # Adjust this if you're using a different package manager

#       - name: Bump version
#         id: bump_version
#         run: |
#           git config user.name akashmishra24
#           git config user.email akashmishra24@users.noreply.github.com
#           TAG=$(echo "${{ steps.get_version.outputs.version }}" | sed 's/^v//')  # Remove the leading 'v'
#           git tag -fa "$TAG" -m "Release $TAG"
#           echo "::set-output name=new_version::$TAG"  # Pass the version as output

#       - name: Push tag
#         run: |
#           git push --force origin ${{ steps.bump_version.outputs.new_version }}

name: Tag Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  tag_release:
    name: Tag the release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to fetch the current version from the package.json or any other version file.
      # Modify this step according to your repository structure.
      - name: Get current version
        id: get_version
        run: echo "::set-output name=version::$(cat version.txt)"  

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # Adjust the version if needed

      - name: Install dependencies
        run: npm install  # Adjust this if you're using a different package manager

      - name: Bump version
        uses: haya14busa/action-update-semver@v1
        id: bump_version
        with:
          tag: ${{ steps.get_version.outputs.version }}  # Use the version from the previous step

      - name: Tag repository
        run: |
          git config user.name akashmishra24
          git config user.email akashmishra24@users.noreply.github.com
          git tag ${{ steps.bump_version.outputs.new_version }} -m "Release ${{ steps.bump_version.outputs.new_version }}"

      - name: Push tags
        run: git push --force origin ${{ steps.bump_version.outputs.new_version }}
