name: 'Bump Version on PR Close'
on:
  pull_request:
    types:
      - closed

jobs:
  bump-version:
    name: 'Bump Version on semver'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Check Commit Message for Version Bump'
        id: check-version-bump
        run: |
          if [[ $(git log --format=%B -n 1 ${{ github.sha }}) =~ (MAJOR|MINOR|PATCH) ]]; then
            echo "::set-output name=bump::true"
          else
            echo "::set-output name=bump::false"
          fi

      - name: 'Automated Version Bump'
        if: steps.check-version-bump.outputs.bump == 'true'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          minor-wording:  'MINOR'
          major-wording:  'MAJOR'
          patch-wording:  'PATCH'
          rc-wording:     'BETA'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        if: steps.check-version-bump.outputs.bump == 'true'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
