name: 'Bump Version'
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    name: 'Bump Version on semver'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'cat package.json'
        run: cat ./package.json
        
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          minor-wording:  'MINOR'
          major-wording:  'MAJOR'
          patch-wording:  'PATCH'
          rc-wording:     'BETA'
        env:
         GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
         
      - name: 'cat package.json'
        run: cat ./package.json
         
      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
