name: Tagging the TF Modules

on:
# Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    paths-ignore: "./github/workflows/tag_modules.yml"
    
  pull_request:
    branches: [ "main" ]
    paths-ignore: "./github/workflows/tag_modules.yml"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  tag_repo:
    name: Get runner id and tag the current code snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tag and push current repo code
        run: |
          git tag ${{github.run_id}}
          git push origin ${{github.run_id}}
