name: 'Bump Version on Merge to Main'
on:
  pull_request:
    types:
      - closed

jobs:
  bump-version:
    name: 'Bump Version on semver'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'Get Merge Commit Message'
        id: get-merge-commit-message
        run: |
          echo "Merge Message: $(git log --format=%B -n 1 ${{ github.event.pull_request.head.sha }})" >> merge_message.txt

      - name: 'Read Merge Commit Message'
        id: read-merge-commit-message
        run: |
          echo "Merge Message: $(cat merge_message.txt)"
        
      - name: 'Automated Version Bump'
        if: ${{ github.event.pull_request.merged == true }}
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
          minor-wording:  'MINOR,minor'
          major-wording:  'MAJOR,major'
          patch-wording:  'PATCH,patch,fixes'
          rc-wording:     'BETA'
          target-branch: 'main'
          commit-message: '${{ steps.read-merge-commit-message.outputs.MERGE_MESSAGE }}'
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
         
      - name: 'cat package.json'
        if: ${{ github.event.pull_request.merged == true }}
        run: cat ./package.json
         
      - name: 'Output Step'
        if: ${{ github.event.pull_request.merged == true }}
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
