name: Create Release Tag

on:
  pull_request:
    types:
      - closed

jobs:
  create-tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v2

      - name: Determine tag version
        id: determine_version
        run: |
          previous_version=$(cat version.txt)
          echo "Current version: $previous_version"

          major_keyword='MAJOR'
          minor_keyword='MINOR'
          patch_keyword='PATCH'

          # Fetch pull request description
          pull_request_description=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
            jq -r '.body')

          echo "Pull request description: $pull_request_description"

          # Perform case-insensitive matching for keywords
          shopt -s nocasematch

          if [[ "$pull_request_description" == *"$major_keyword"* ]]; then
            new_version=$(echo $previous_version | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\1/')
            new_version=$((new_version + 1))
            new_tag="v${new_version}.0.0"
          elif [[ "$pull_request_description" == *"$minor_keyword"* ]]; then
            new_version=$(echo $previous_version | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\2/')
            new_version=$((new_version + 1))
            new_tag=$(echo $previous_version | sed -E "s/v[0-9]+\.[0-9]+\.[0-9]+/v0.${new_version}.0/")
          elif [[ "$pull_request_description" == *"$patch_keyword"* ]]; then
            new_version=$(echo $previous_version | sed -E 's/v([0-9]+)\.([0-9]+)\.([0-9]+)/\3/')
            new_version=$((new_version + 1))
            new_tag=$(echo $previous_version | sed -E "s/v[0-9]+\.[0-9]+\.[0-9]+/v0.0.${new_version}/")
          else
            echo "No keyword found in the pull request description. Skipping tag creation."
            exit 0
          fi

          # Disable case-insensitive matching
          shopt -u nocasematch

          echo "New tag version: $new_tag"
          echo "NEW_TAG=$new_tag" >> $GITHUB_ENV

      - name: Create Git tag
        if: env.NEW_TAG != 'v0.0.0'
        run: |
          git tag $NEW_TAG
          git push origin $NEW_TAG
