name: 'Bump Version on PR Close and Merge to Main'
on:
  pull_request:
    types:
      - closed

jobs:
  bump-version:
    name: 'Bump Version on semver'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'Get Merge Commit Message'
        id: get-merge-commit-message
        run: |
          MERGE_COMMIT_SHA=$GITHUB_SHA
          MERGE_COMMIT_MESSAGE=$(git log --format=%B -n 1 $MERGE_COMMIT_SHA)
          echo "Merge Message: $MERGE_COMMIT_MESSAGE" >> merge_message.txt

      - name: 'Read Merge Commit Message'
        id: read-merge-commit-message
        run: |
          echo "Merge Message: $(cat merge_message.txt)"
        
      - name: 'Automated Version Bump'
        if: ${{ github.event.pull_request.merged == true }}
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          minor-wording:  'add,Adds,new'
          major-wording:  'MAJOR,cut-major'
          patch-wording:  'patch,fixes'
          rc-wording:     'RELEASE,alpha'
          bump-policy: 'all'
          skip-tag: 'false'
          skip-commit: 'false'
          skip-push: 'false'
          PACKAGEJSON_DIR: '.'  # If your package.json is not in the root directory, specify its location here
          target-branch: 'main'
          check-last-commit-only: 'true'
          commit-message: '${{ steps.read-merge-commit-message.outputs.MERGE_MESSAGE }}'  # Use the fetched merge commit message
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         
      - name: 'cat package.json'
        if: ${{ github.event.pull_request.merged == true }}
        run: cat ./package.json
         
      - name: 'Output Step'
        if: ${{ github.event.pull_request.merged == true }}
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"
