name: 'Bump Version on PR Close and Merge to Main'
on:
  pull_request:
    types:
      - closed

jobs:
  get-commits:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'Get Commit Messages'
        id: get-commits
        run: |
          echo "COMMIT_MESSAGES=$(git log --pretty=%B)" >> $GITHUB_ENV

  bump-version:
    name: 'Bump Version on semver'
    needs: get-commits
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'

      - name: 'Run Bump Version Action'
        if: github.event.pull_request.merged == true  # Only run the action on merged pull requests
        id: bump-version
        uses: 'akashmishra24/gh-action-bump-version@main'
        with:
          minor-wording: 'add,Adds,new'
          major-wording: 'MAJOR,cut-major'
          patch-wording: 'patch,fixes'
          rc-wording: 'RELEASE,alpha'
          PACKAGEJSON_DIR: '.'  # If your package.json is not in the root directory, specify its location here
          target-branch: 'main'
          commit-message: ${{ env.COMMIT_MESSAGES }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
