name: Terratest Unit Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
# test
  workflow_dispatch:
jobs:
  go-tests:
    name: Run Go Unit Tests (terratest)
    runs-on: ubuntu-latest #self-hosted
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.19.4
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false
      - name: Install azure-cli
        uses: pietrobolcato/install-azure-cli-action@v1
      - name: Azure Login
        run: |
          az login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Download Go modules
        working-directory: key_vault/test
        run: go mod download
      - name: Run tests
        working-directory: key_vault/test
        run: go test -tags azure .
