name: Terratest Unit Tests
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  go-tests:
    name: Run Go Unit Tests (terratest)
    runs-on: ubuntu-latest #self-hosted
    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
    #env:
    #  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
    #  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
    #  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    #  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: 1.19.4
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.6
          terraform_wrapper: false
      - name: Download Go modules
        working-directory: storage_account_module/test
        run: go mod download
      #- name: 'Az CLI login'
      #  uses: azure/login@v1
      #  with:
      #    client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
      #    tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
      #    subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #    client-secret: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      #- uses: Azure/login@v1
      #  with:
      #    creds: '{"clientId":"${{ secrets.AZURE_AD_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_AD_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_AD_TENANT_ID }}"}'
      - name: Run tests
        working-directory: storage_account_module/test
        run: go test -v -tags=unit
        #env:
        #  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        #  ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        #  AZURE_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
        #  ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        #  AZURE_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
        #  ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
        #  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
          
