name: Release

on:
  push:
    branches:
      - main
      
defaults:
  run:
    shell: bash
    working-directory: 'azure_kubernetes_service'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 13
    - name: Add plugin for conventional commits
      run: npm install conventional-changelog-conventionalcommits
      working-directory: ./.github/workflows
    - name: Release to GitHub
      working-directory: ./.github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_AUTHOR_NAME: enter author name
        GIT_AUTHOR_EMAIL: person@example.com
        GIT_COMMITTER_NAME: enter name
        GIT_COMMITTER_EMAIL: committer@example.com
      run: npx semantic-release
